import { Montserrat } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';
import { Session } from 'next-auth';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function SessionProvidersWrapper({ children, session }: { children: React.ReactNode; session: Session }) {
    return <SessionProvider session={session}>{children}</SessionProvider>;
}
